# Created with komac v2.6.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Zoom.ZoomRooms
PackageVersion: 6.2.7
Scope: machine
UpgradeBehavior: install
Protocols:
- zoomroom
ReleaseDate: 2024-12-02
Installers:
- Architecture: x64
  InstallerType: exe
  InstallerUrl: https://cdn.zoom.us/prod/6.2.7.5001/x64/zoomrooms-6.2.7.5001-x64.exe
  InstallerSha256: 9825C1A7EE0E5FAA346DB46EBAC4B66412D697881AFB0EF3556E6A6D242F10FB
  InstallModes:
  - interactive
  - silent
  - silentWithProgress
  InstallerSwitches:
    Silent: /accept_gdpr /silent
    SilentWithProgress: /accept_gdpr
    Custom: /no_autorun
- InstallerLocale: und
  Architecture: x64
  InstallerType: msi
  InstallerUrl: https://cdn.zoom.us/prod/6.2.7.5001/x64/zoomrooms-6.2.7.5001-x64.msi
  InstallerSha256: EDC655C8780419240C09FFE61A454266378B99782EB4B89287FC388095DC8542
  InstallerSwitches:
    Silent: /passive ACCEPTGDPR=true SILENT=true
    SilentWithProgress: /passive ACCEPTGDPR=true
    Custom: AUTOSTART=false
  ProductCode: '{2EAD473B-5B4A-4B49-92D7-94C60C34E3EA}'
  UnsupportedArguments:
  - log
  AppsAndFeaturesEntries:
  - DisplayName: Zoom Rooms Installer
    Publisher: Zoom Video Communications, Inc.
    ProductCode: '{2EAD473B-5B4A-4B49-92D7-94C60C34E3EA}'
    UpgradeCode: '{F209929A-557A-4F8E-B453-6B668E1B9799}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\ZoomRooms\Installer'
ManifestType: installer
ManifestVersion: 1.6.0
